services:
  - type: web
    name: scholarviews
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
