services:
  - type: web
    name: scholarviews
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn routes:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
